name: Flutter CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flutter-version: [ "2.10.4" ] # Change this to the desired Flutter version
        api-level: [ 29 ] # Change this to the desired API level

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ matrix.flutter-version }}

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -O cmdline-tools.zip
        sudo mkdir -p /usr/local/android-sdk/cmdline-tools
        sudo unzip -q cmdline-tools.zip -d /usr/local/android-sdk/cmdline-tools
        sudo mv /usr/local/android-sdk/cmdline-tools/cmdline-tools /usr/local/android-sdk/cmdline-tools/latest
        sudo yes | /usr/local/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        /usr/local/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "emulator" "system-images;android-30;default;x86_64"

    - name: Set up Android emulator
      run: |
        sudo /usr/local/android-sdk/cmdline-tools/latest/bin/sdkmanager --update
        echo "y" | sudo /usr/local/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        sudo /usr/local/android-sdk/emulator/emulator -list-avds
        sudo /usr/local/android-sdk/emulator/emulator -avd test -no-window -no-audio -no-boot-anim -gpu off &

    - name: Wait for Android emulator to start
      run: |
        adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
      timeout-minutes: 10

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test

    - name: Run integration tests
      run: flutter drive --target=test_driver/app.dart
