name: Flutter CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flutter-version: [ "3.4.1" ] # Change this to the desired Flutter version

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ matrix.flutter-version }}

    - name: Install dependencies
      run: |
        cd frontend/jastip
        flutter pub get

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -O cmdline-tools.zip
        sudo mkdir -p /usr/local/android-sdk/cmdline-tools
        sudo unzip -q cmdline-tools.zip -d /usr/local/android-sdk/cmdline-tools
        sudo mv /usr/local/android-sdk/cmdline-tools/cmdline-tools /usr/local/android-sdk/cmdline-tools/latest
        sudo yes | /usr/local/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        /usr/local/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "emulator" "system-images;android-30;default;x86_64"

    - name: Set up environment
      run: echo "ANDROID_SDK_ROOT=/usr/local/android-sdk" >> $GITHUB_ENV

    - name: Create AVD
      run: echo "no" | /usr/local/android-sdk/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-30;default;x86_64" -d "pixel"

    - name: Start emulator
      env:
        ANDROID_SDK_ROOT: /usr/local/android-sdk
      run: |
        sudo $ANDROID_SDK_ROOT/emulator/emulator -avd test -no-snapshot -no-window -no-audio -gpu swiftshader -accel on &
        adb wait-for-device
        adb shell input keyevent 82

    - name: Run tests
      env:
        DISPLAY: ":0"
      run: flutter drive --target=test_driver/app.dart
